name: Aviator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: npm --prefix frontend install

    - name: Run Frontend Linter
      run: npm --prefix frontend run lint

    - name: Run Frontend Tests
      run: npm --prefix frontend run test

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Backend Linter
      run: |
        pip install flake8
        flake8 backend/

    - name: Run Backend Tests
      run: echo "Pytest tests would run here"

    - name: Build Docker images (optional)
      run: echo "Docker build would run here"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: |
          frontend/dist
          backend/staticfiles
